In [27]:
import numpy as np
from scipy.spatial import distance
# 距离函数
# def dis_abs(x,y):
#     return distance.cdist(x, y, 'euclidean')
# DTW 的代码实现
def dtw(dist):
    N_A = dist.shape[0]
    N_B = dist.shape[1]
    
    D =np.zeros([N_A,N_B])
    D[0,0]=2*dist[0][0]
    
    # 左边一列
    for i in range(1,N_A):
        D[i,0] = D[i-1,0]+dist[i][0]
        
    # 下面的一行
    for j in range(1,N_B):
         D[0,j] = D[0,j-1]+dist[0][j]
    
    #中间部分
    for i in range(1,N_A):
        for j in range(1,N_B):
            D[i,j]=min(D[i-1,j]+dist[i][j],D[i,j-1]+dist[i][j],D[i-1,j-1]+2*dist[i][j])
    
    #路径回测
    i = N_A-1
    j = N_B-1
    count = 0
    d = np.zeros(max(N_A,N_B)*3)
    #print(d)
    path = []
    while True:
        if i>0 and j>0:
            path.append((i,j))
            m = min(D[i-1,j],D[i,j-1],D[i-1,j-1])

            if  m == D[i-1,j-1]:
                d[count]=D[i,j] - 2*dist[i][j]
                i = i-1
                j = j-1
                count = count + 1

            elif  m == D[i,j-1]:
                d[count]=D[i,j] - dist[i,j-1]
                j = j-1
                count = count + 1
 
            elif  m == D[i-1,j]:
                d[count]=D[i,j] - dist[i-1,j]
                i = i-1
                count = count + 1

        elif i == 0 and j == 0:
            path.append((i,j))
            d[count] = D[i,j]
            count = count + 1
            break

        elif i == 0:
            path.append((i,j))
            d[count]=D[i,j] - dist[i,j-1]
            j = j-1
            count = count + 1

        elif j == 0:
            path.append((i,j))
            d[count]=D[i,j] - dist[i-1,j]
            i = i-1
            count = count + 1

    mean = np.sum(d)/count
    return mean,path[::-1],D    

In [28]:
import numpy as np
a = np.array([[2,1,5,1],[3,4,8,2],[5,2,4,3],[4,7,2,4],[1,5,1,6],[2,1,7,5]])  # cost距离矩阵
# a = a[:,np.newaxis]
# b = b[:,np.newaxis]
#print(a[0][0])
dis,path,D = dtw(a)
print(dis)
print(path)
print(D)

9.5
[(0, 0), (1, 0), (2, 1), (3, 2), (4, 2), (5, 3)]
[[ 4.  5. 10. 11.]
 [ 7.  9. 17. 13.]
 [12. 11. 15. 16.]
 [16. 18. 15. 19.]
 [17. 22. 16. 22.]
 [19. 19. 23. 26.]]
