In [22]:
import numpy as np
from scipy.spatial import distance
# 距离函数
def dis_abs(x,y):
    return distance.cdist(x, y, 'euclidean')
# DTW 的代码实现
def dtw(A,B,dis_func=dis_abs):
    N_A = len(A)
    N_B = len(B)
    dist = dis_func(A,B)
    D =np.zeros([N_A,N_B])
    D[0,0]=dist[0][0]
    
    # 左边一列
    for i in range(1,N_A):
        D[i,0] = D[i-1,0]+dist[i][0]
        
    # 下面的一行
    for j in range(1,N_B):
         D[0,j] = D[0,j-1]+dist[0][j]
    
    #中间部分
    for i in range(1,N_A):
        for j in range(1,N_B):
            D[i,j]=dist[i][j]+min(D[i-1,j],D[i,j-1],D[i-1,j-1])
    
    #路径回测
    i = N_A-1
    j = N_B-1
    count = 0
    d = np.zeros(max(N_A,N_B)*3)
    #print(d)
    path = []
    while True:
        if i>0 and j>0:
            path.append((i,j))
            m = min(D[i-1,j],D[i,j-1],D[i-1,j-1])

            if  m == D[i-1,j-1]:
                d[count]=D[i,j] - D[i-1,j-1]
                i = i-1
                j = j-1
                count = count + 1

            elif  m == D[i,j-1]:
                d[count]=D[i,j] - D[i,j-1]
                j = j-1
                count = count + 1
 
            elif  m == D[i-1,j]:
                d[count]=D[i,j] - D[i-1,j]
                i = i-1
                count = count + 1

        elif i == 0 and j == 0:
            path.append((i,j))
            d[count] = D[i,j]
            count = count + 1
            break

        elif i == 0:
            path.append((i,j))
            d[count]=D[i,j] - D[i,j-1]
            j = j-1
            count = count + 1

        elif j == 0:
            path.append((i,j))
            d[count]=D[i,j] - D[i-1,j]
            i = i-1
            count = count + 1

    mean = np.sum(d)/count
    return mean,path[::-1],D    

In [23]:
import numpy as np
a = [(0,2),(1,3),(2,5),(3,2),(4,7),(5,8),(6,9)]   # x的矩阵竖直0到n-1共n个点
b = [(1,2),(2,3),(3,4),(5,6),(7,8)]               # y的矩阵水平0到n-1共n个点
#print(a,b)
# a = a[:,np.newaxis]
# b = b[:,np.newaxis]
#print(a,b)
dis,path,D = dtw(a,b,dis_func=dis_abs)
print(dis)
print(path)
print(D)

1.4632343838741837
[(0, 0), (1, 1), (2, 2), (3, 2), (4, 3), (5, 3), (6, 4)]
[[ 1.          3.23606798  6.84161925 13.24474349 22.46428795]
 [ 2.          2.          4.23606798  9.23606798 17.04631765]
 [ 5.16227766  4.          3.41421356  6.57649122 12.40744312]
 [ 7.16227766  5.41421356  5.41421356  7.88634952 13.78759377]
 [12.99322956  9.88634952  8.57649122  6.82842712  9.99070478]
 [20.20433211 15.71730141 13.04862718  8.82842712  8.82842712]
 [28.80665737 22.92840396 18.87957907 11.99070478 10.24264069]]
