In [7]:
import numpy as np
# 距离函数
def dis_abs(x,y):
    return abs(x-y)
# DTW 的代码实现
def dtw(A,B,dis_func=dis_abs):
    N_A = len(A)
    N_B = len(B)
    
    D =np.zeros([N_A,N_B])
    D[0,0]=dis_func(A[0],B[0])
    
    # 左边一列
    for i in range(1,N_A):
        D[i,0] = D[i-1,0]+dis_func(A[i],B[0])
        
    # 下面的一行
    for j in range(1,N_B):
         D[0,j] = D[0,j-1]+dis_func(A[0],B[j])
    
    #中间部分
    for i in range(1,N_A):
        for j in range(1,N_B):
            D[i,j]=dis_func(A[i],B[j])+min(D[i-1,j],D[i,j-1],D[i-1,j-1])
    
    #路径回测
    i = N_A-1
    j = N_B-1
    count = 0
    d = np.zeros(max(N_A,N_B)*3)
    #print(d)
    path = []
    while True:
        if i>0 and j>0:
            path.append((i,j))
            m = min(D[i-1,j],D[i,j-1],D[i-1,j-1])

            if  m == D[i-1,j-1]:
                d[count]=D[i,j] - D[i-1,j-1]
                i = i-1
                j = j-1
                count = count + 1

            elif  m == D[i,j-1]:
                d[count]=D[i,j] - D[i,j-1]
                j = j-1
                count = count + 1
 
            elif  m == D[i-1,j]:
                d[count]=D[i,j] - D[i-1,j]
                i = i-1
                count = count + 1

        elif i == 0 and j == 0:
            path.append((i,j))
            d[count] = D[i,j]
            count = count + 1
            break

        elif i == 0:
            path.append((i,j))
            d[count]=D[i,j] - D[i,j-1]
            j = j-1
            count = count + 1

        elif j == 0:
            path.append((i,j))
            d[count]=D[i,j] - D[i-1,j]
            i = i-1
            count = count + 1

    mean = np.sum(d)/count
    return mean,path[::-1],D    

In [8]:
import numpy as np
a = np.array([1,3,4,9,8,2,1,5,7,3])
b = np.array([1,6,2,3,0,9,4,1,6,3])
#print(a,b)
#增加一维
a = a[:,np.newaxis]
b = b[:,np.newaxis]
#print(a,b)
dis,path,D = dtw(a,b,dis_func=dis_abs)
print(dis)
print(path)
print(D)

1.0833333333333333
[(0, 0), (1, 1), (1, 2), (1, 3), (2, 4), (3, 5), (4, 5), (5, 6), (6, 7), (7, 8), (8, 8), (9, 9)]
[[ 0.  5.  6.  8.  9. 17. 20. 20. 25. 27.]
 [ 2.  3.  4.  4.  7. 13. 14. 16. 19. 19.]
 [ 5.  4.  5.  5.  8. 12. 12. 15. 17. 18.]
 [13.  7. 11. 11. 14.  8. 13. 20. 18. 23.]
 [20.  9. 13. 16. 19.  9. 12. 19. 20. 23.]
 [21. 13.  9. 10. 12. 16. 11. 12. 16. 17.]
 [21. 18. 10. 11. 11. 19. 14. 11. 16. 18.]
 [25. 19. 13. 12. 16. 15. 15. 15. 12. 14.]
 [31. 20. 18. 16. 19. 17. 18. 21. 13. 16.]
 [33. 23. 19. 16. 19. 23. 18. 20. 16. 13.]]
